//这是一个公共布局文件夹
import "./styles/globals.css";
// //这是页脚的按钮组件
// import Footer from "../components/Footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
